apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - DAC_READ_SEARCH
              - DAC_OVERRIDE
              - SYS_ADMIN
              - NET_BIND_SERVICE
              - SETGID
              - SETUID
              - CHOWN
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
